### ISSUE TITLE
feat: 各スライドをslides.mdからインポートする形で差し替える

### ISSUE THREAD

**Issue by kyonenya** [kyonenya/slides#1]
- [Importing Slides | Slidev](https://sli.dev/features/importing-slides) を使う
  - JavaScript で言うところの「index.js にはインポート文しか書かれてない」みたいな運用にする
  - 毎回、発表ごとに _slides-240916.md みたいなファイルがプロジェクトルートに増えていくのが嫌だった
- フロントマターにもインポート文を書くと、表紙ページ（フロントマターの次ページ）からインポートできる
- [Frontmatter Merging | Slidev](https://sli.dev/features/frontmatter-merging) でプロパティもマージされる、はずなのだが……
  - 実験してみると、theme, fonts, download などの重要項目はインポート不可能だったのでルートに書くようにする
  - title, background はインポート可能だったので個別に書く

**Comment by kyonenya** [comment]
f496203f672f83ec9915e5f955939adfc988c3b6

**Comment by kyonenya** [comment]
FrontMatter にこう書くだけで丸ごとインポートできた

```
---
theme: seriph
fonts:
  sans: Noto Sans JP
  serif: Noto Serif JP
download: true
src: ./pages/240916-博論の全体構成.md
---
```
